<?php
/*
 * @file
 * Example tutorial from NodeOne tutorials , math question module.
 */
/**
 * Implements hook_menu().
 */
function mathquestion_menu() {
  
  $items['question'] = array(
    'title' => 'Math Question',
    'description' => 'Mathquestion Description.... :) ',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mathquestion_page'),
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'menu_name' => 'management',
    'weight' => -6,
  );
  return $items;
}
/**
 * Building the user-interface (the form).
 */
function mathquestion_page($form, &$form_state) {
  //Randomly assign 2 variables and them store the sum in $total.  
  $val1 = rand(1,10);
  $val2 = rand(1,10);
  $total = $val1 + $val2;
    //hidden form field value
  $form['nr1'] = array(
    '#type' => 'value',
    '#value' => $val1,
  );
  //hidden form field value2
  $form['nr2'] = array(
    '#type' => 'value',
    '#value' => $val2,
  );
  $form['correct_answer'] = array(
    '#type' => 'hidden',
    '#value' => $total,
  );
  //form field for the question
  $form['form_question'] = array(
    '#type' => 'item',
    '#markup' => 'What is ' . $val1 . ' + ' . $val2 . '?',
  );
  //form field for the input of the answer
  $form['answer_inputed'] = array(
    '#type' => 'textfield',
    '#title' => t('Answer Here:'),
    '#description' => t('Translatable description here !'),
  );
  // The form submit field.
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Check my answer !')
  );
  $form_state['redirect'] = false;
  return $form;
}
/**
 * Submit function for the Mathquestion page (user interface).
 */
function mathquestion_page_validate($form, &$form_state) {

   if ($form_state['input']['correct_answer'] == $form_state['input']['answer_inputed']){
     dpm('Your answer is correct !');
   }else{ 
     form_set_error('answer_inputed', t('Wrong Answer !!!' ));
   }
}
